name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: MrIsimael
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
          mode: pacman
          color_snake: '#39D353'          # Pac-Man color (GitHub green)
          background_color: '#0D1117'     # GitHub dark mode background
          color_grid: '#161B22'           # GitHub dark mode contribution grid

      - name: Push SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
